/**
 * Data Layer — handles all data fetching, transforming, and caching
 * NO React dependencies, pure functions
 */

import type { Player, LeagueConfig, DraftData, BattingStats, PitchingStats } from '../types';

/**
 * Load draft data from public JSON (generated by cron job)
 */
export async function loadDraftData(): Promise<DraftData> {
  const res = await fetch('./data/draft-data.json');
  if (!res.ok) throw new Error(`Failed to load draft data: ${res.statusText}`);
  return res.json();
}

/**
 * Filter players by position
 */
export function filterByPosition(players: Player[], position: string): Player[] {
  if (position === 'ALL') return players;
  return players.filter(p => p.position === position || p.positions?.includes(position as any));
}

/**
 * Filter players by type (batter/pitcher)
 */
export function filterByType(players: Player[], type: 'batter' | 'pitcher' | 'ALL'): Player[] {
  if (type === 'ALL') return players;
  return players.filter(p => p.type === type);
}

/**
 * Filter players by tier
 */
export function filterByTier(players: Player[], tier: string): Player[] {
  if (tier === 'ALL') return players;
  return players.filter(p => p.tier === tier);
}

/**
 * Search players by name
 */
export function searchByName(players: Player[], query: string): Player[] {
  if (!query.trim()) return players;
  const lower = query.toLowerCase();
  return players.filter(p => p.name.toLowerCase().includes(lower));
}

/**
 * Sort players by various criteria
 */
export function sortPlayers(
  players: Player[],
  sortBy: 'name' | 'adp' | 'ops' | 'k' | 'tier',
  direction: 'asc' | 'desc' = 'asc'
): Player[] {
  const sorted = [...players];
  const mult = direction === 'asc' ? 1 : -1;

  sorted.sort((a, b) => {
    let aVal: any, bVal: any;
    
    switch (sortBy) {
      case 'name':
        aVal = a.name;
        bVal = b.name;
        return (aVal < bVal ? -1 : aVal > bVal ? 1 : 0) * mult;
      case 'adp':
        aVal = a.adp || Infinity;
        bVal = b.adp || Infinity;
        return (aVal - bVal) * mult;
      case 'ops':
        aVal = a.batting?.ops || -1;
        bVal = b.batting?.ops || -1;
        return (aVal - bVal) * mult;
      case 'k':
        aVal = a.pitching?.k || -1;
        bVal = b.pitching?.k || -1;
        return (aVal - bVal) * mult;
      case 'tier':
        const tierOrder = { ELITE: 0, '1': 1, '2': 2, '3': 3, '4': 4, '5': 5 };
        aVal = tierOrder[a.tier as keyof typeof tierOrder] || 99;
        bVal = tierOrder[b.tier as keyof typeof tierOrder] || 99;
        return (aVal - bVal) * mult;
      default:
        return 0;
    }
  });

  return sorted;
}

/**
 * Calculate value over replacement (simple position-based VOR)
 * Returns object mapping player ID to VOR score
 */
export function calculateVOR(
  players: Player[],
  leagueConfig: LeagueConfig
): Record<string, number> {
  const vor: Record<string, number> = {};
  const batters = players.filter(p => p.type === 'batter');
  const pitchers = players.filter(p => p.type === 'pitcher');

  // Replacement level: median player at that position
  const batterReplacements: Record<string, number> = {};
  const pitcherReplacements: Record<string, number> = {};

  // Calculate median OPS for each position
  ['C', '1B', '2B', '3B', 'SS', 'OF', 'DH'].forEach(pos => {
    const posPlayers = batters.filter(p => p.position === pos || p.positions?.includes(pos as any));
    if (posPlayers.length > 0) {
      const sorted = posPlayers
        .filter(p => p.batting?.ops)
        .sort((a, b) => (b.batting?.ops || 0) - (a.batting?.ops || 0));
      const replIdx = Math.floor(sorted.length * 0.5);
      batterReplacements[pos] = sorted[replIdx]?.batting?.ops || 0;
    }
  });

  // For pitchers, use K% as primary metric
  const sortedPitchers = pitchers
    .filter(p => p.pitching?.kpct)
    .sort((a, b) => (b.pitching?.kpct || 0) - (a.pitching?.kpct || 0));
  const pitcherReplacement = sortedPitchers[Math.floor(sortedPitchers.length * 0.5)]?.pitching?.kpct || 0;

  // Calculate VOR
  batters.forEach(p => {
    if (!p.batting?.ops) {
      vor[p.id] = 0;
      return;
    }
    const replacement = batterReplacements[p.position] || 0.700;
    vor[p.id] = (p.batting.ops - replacement) * 100; // scale for readability
  });

  pitchers.forEach(p => {
    if (!p.pitching?.kpct) {
      vor[p.id] = 0;
      return;
    }
    vor[p.id] = (p.pitching.kpct - pitcherReplacement) * 100;
  });

  return vor;
}

/**
 * Get tier breakdown summary: count and average metrics per tier
 */
export interface TierSummary {
  tier: string;
  count: number;
  avgOps?: number;
  avgK?: number;
}

export function getTierBreakdown(players: Player[]): TierSummary[] {
  const tiers: Record<string, Player[]> = {};
  
  players.forEach(p => {
    if (!tiers[p.tier]) tiers[p.tier] = [];
    tiers[p.tier].push(p);
  });

  return Object.entries(tiers)
    .sort(([a], [b]) => {
      const order = { ELITE: 0, '1': 1, '2': 2, '3': 3, '4': 4, '5': 5 };
      return (order[a as any] || 99) - (order[b as any] || 99);
    })
    .map(([tier, tierPlayers]) => {
      const batters = tierPlayers.filter(p => p.batting?.ops);
      const pitchers = tierPlayers.filter(p => p.pitching?.k);
      
      return {
        tier,
        count: tierPlayers.length,
        avgOps: batters.length > 0 
          ? batters.reduce((sum, p) => sum + (p.batting?.ops || 0), 0) / batters.length
          : undefined,
        avgK: pitchers.length > 0
          ? pitchers.reduce((sum, p) => sum + (p.pitching?.k || 0), 0) / pitchers.length
          : undefined,
      };
    });
}
